/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package presentacion;

/**
 *
 * @author CSjes
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        Animacion.Animacion.mover_izquierda(261, 5, 2, 2, jbDesplegarMenu);
        Animacion.Animacion.mover_izquierda(5, -261, 2, 2, jpMenu);
        lblMarcaA.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jbMenuUsuarios = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbMenuPuntoCobro = new javax.swing.JButton();
        jbMenuInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbDesplegarMenu = new javax.swing.JButton();
        jbCerrrar = new javax.swing.JButton();
        lblMarcaA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 159, 220));
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(117, 199, 255));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbMenuUsuarios.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuUsuarios.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario (2).png"))); // NOI18N
        jbMenuUsuarios.setText("Usuarios");
        jbMenuUsuarios.setBorder(null);
        jbMenuUsuarios.setContentAreaFilled(false);
        jbMenuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMenuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuUsuariosMouseClicked(evt);
            }
        });
        jpMenu.add(jbMenuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 40));

        jbSalir.setBackground(new java.awt.Color(252, 195, 20));
        jbSalir.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsesion32px.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.setBorder(null);
        jbSalir.setContentAreaFilled(false);
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jpMenu.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 260, 40));

        jbMenuPuntoCobro.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuPuntoCobro.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuPuntoCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/puntocobro32px.png"))); // NOI18N
        jbMenuPuntoCobro.setText("Punto de Cobro");
        jbMenuPuntoCobro.setBorder(null);
        jbMenuPuntoCobro.setContentAreaFilled(false);
        jbMenuPuntoCobro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMenuPuntoCobro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuPuntoCobroMouseClicked(evt);
            }
        });
        jbMenuPuntoCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuPuntoCobroActionPerformed(evt);
            }
        });
        jpMenu.add(jbMenuPuntoCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 260, 40));

        jbMenuInventario.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuInventario.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario (1).png"))); // NOI18N
        jbMenuInventario.setText("Inventario");
        jbMenuInventario.setBorder(null);
        jbMenuInventario.setContentAreaFilled(false);
        jbMenuInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuInventarioMouseClicked(evt);
            }
        });
        jbMenuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuInventarioActionPerformed(evt);
            }
        });
        jpMenu.add(jbMenuInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 40));

        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPapeleria2.jpg"))); // NOI18N
        jpMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel5.add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jbDesplegarMenu.setBackground(new java.awt.Color(1, 159, 220));
        jbDesplegarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_icon_2_icon-icons.com_71856.png"))); // NOI18N
        jbDesplegarMenu.setBorder(null);
        jbDesplegarMenu.setContentAreaFilled(false);
        jbDesplegarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbDesplegarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesplegarMenuActionPerformed(evt);
            }
        });
        jPanel5.add(jbDesplegarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 0, 40, 40));

        jbCerrrar.setBackground(new java.awt.Color(2, 159, 220));
        jbCerrrar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jbCerrrar.setText("X");
        jbCerrrar.setBorder(null);
        jbCerrrar.setContentAreaFilled(false);
        jbCerrrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCerrrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCerrrarMouseExited(evt);
            }
        });
        jbCerrrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrrarActionPerformed(evt);
            }
        });
        jPanel5.add(jbCerrrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 40, 40));

        lblMarcaA.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblMarcaA.setForeground(new java.awt.Color(204, 204, 204));
        lblMarcaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarcaA.setText("Papeleria Yolis");
        jPanel5.add(lblMarcaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 940, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDesplegarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesplegarMenuActionPerformed
        int posicion = jbDesplegarMenu.getX();
        if (posicion > 5) {
            Animacion.Animacion.mover_izquierda(261, 5, 2, 2, jbDesplegarMenu);
            Animacion.Animacion.mover_izquierda(5, -261, 2, 2, jpMenu);
            lblMarcaA.setVisible(true);
        } else {
            Animacion.Animacion.mover_derecha(5, 260, 2, 2, jbDesplegarMenu);
            Animacion.Animacion.mover_derecha(-260, 0, 2, 2, jpMenu);
            lblMarcaA.setVisible(false);
        }
    }//GEN-LAST:event_jbDesplegarMenuActionPerformed

    private void jbCerrrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbCerrrarActionPerformed

    private void jbMenuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuInventarioMouseClicked
        hide();
        MenuInventario obmu = new MenuInventario();
        obmu.setVisible(true);
    }//GEN-LAST:event_jbMenuInventarioMouseClicked

    private void jbMenuPuntoCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuPuntoCobroActionPerformed
        hide();
        MenuPuntoCobro objc = new MenuPuntoCobro();
        objc.setVisible(true);
    }//GEN-LAST:event_jbMenuPuntoCobroActionPerformed

    private void jbMenuPuntoCobroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuPuntoCobroMouseClicked

    }//GEN-LAST:event_jbMenuPuntoCobroMouseClicked

    private void jbMenuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuUsuariosMouseClicked
        hide();
        MenuUsuarios obmu = new MenuUsuarios();
        obmu.setVisible(true);
    }//GEN-LAST:event_jbMenuUsuariosMouseClicked

    private void jbCerrrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrrarMouseEntered

    }//GEN-LAST:event_jbCerrrarMouseEntered

    private void jbCerrrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrrarMouseExited

    }//GEN-LAST:event_jbCerrrarMouseExited

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbMenuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMenuInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbCerrrar;
    private javax.swing.JButton jbDesplegarMenu;
    private javax.swing.JButton jbMenuInventario;
    private javax.swing.JButton jbMenuPuntoCobro;
    private javax.swing.JButton jbMenuUsuarios;
    private javax.swing.JButton jbSalir;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JLabel lblMarcaA;
    // End of variables declaration//GEN-END:variables

}
