/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import database.Conexion;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author CSjes
 */
public class VendedorRegistros extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form VendedorRegistros
     */
    public VendedorRegistros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreVendedor = new javax.swing.JLabel();
        txtNombreVendedor = new javax.swing.JTextField();
        lblSexoVendedor = new javax.swing.JLabel();
        txtSexoVendedor = new javax.swing.JTextField();
        lblDomicilioVendedor = new javax.swing.JLabel();
        txtDomicilioVendedor = new javax.swing.JTextField();
        lblCorreoVendedor = new javax.swing.JLabel();
        txtCorreoVendedor = new javax.swing.JTextField();
        lblContraseñaVendedor = new javax.swing.JLabel();
        txtContrasenaVendedor = new javax.swing.JPasswordField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        imgVendedor = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Backgroun = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblNombreVendedor.setText("Nombre :");
        getContentPane().add(lblNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, -1));

        txtNombreVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtNombreVendedor.setBorder(null);
        getContentPane().add(txtNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        lblSexoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblSexoVendedor.setText("Sexo :");
        getContentPane().add(lblSexoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, -1));

        txtSexoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtSexoVendedor.setBorder(null);
        txtSexoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSexoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, -1));

        lblDomicilioVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblDomicilioVendedor.setText("Domicilio :");
        getContentPane().add(lblDomicilioVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, -1));

        txtDomicilioVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtDomicilioVendedor.setBorder(null);
        getContentPane().add(txtDomicilioVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, -1));

        lblCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblCorreoVendedor.setText("Correo :");
        getContentPane().add(lblCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, -1));

        txtCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtCorreoVendedor.setBorder(null);
        getContentPane().add(txtCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, -1));

        lblContraseñaVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblContraseñaVendedor.setText("Contraseña :");
        getContentPane().add(lblContraseñaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, -1));

        txtContrasenaVendedor.setText("jPasswordField1");
        txtContrasenaVendedor.setBorder(null);
        getContentPane().add(txtContrasenaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, 30));

        lblID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblID.setText("ID :");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 20, -1));

        txtID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtID.setBorder(null);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 70, -1));

        imgVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        imgVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor128px.png"))); // NOI18N
        getContentPane().add(imgVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 130, 130));

        btnAgregar.setBackground(new java.awt.Color(254, 192, 15));
        btnAgregar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        Backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVendedores.png"))); // NOI18N
        Backgroun.setPreferredSize(new java.awt.Dimension(460, 670));
        getContentPane().add(Backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 240, 460));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1491254409-leftarrowbackwardsign_82959.png"))); // NOI18N
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.setPreferredSize(new java.awt.Dimension(32, 32));
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendedor");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 310, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(240, 240, 240)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSexoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoVendedorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion conn = Conexion.getInstance();
        PreparedStatement ps;
        if( txtID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoría");
            txtID.requestFocus();
            return;
        }
        String consultaSQL;
        consultaSQL = "INSERT INTO Vendedores(NombreVendedor,SexoVendedor, DomicilioVendedor, CorreoVendedor, ContrasenaVendedor,ImagenVendedor, activo)\n";
        consultaSQL +="VALUES(?,?,?,?,?,?,?)";
        try
        {
            conn.Conectar();
            ps=conn.cadena.prepareStatement(consultaSQL);
            ps.setString(1,txtNombreVendedor.getText().trim());
            ps.setString(2, txtSexoVendedor.getText().trim());
            ps.setString(3, txtDomicilioVendedor.getText().trim());
            ps.setString(4, txtCorreoVendedor.getText().trim());
            ps.setString(5, String.valueOf(txtContrasenaVendedor.getPassword()).trim());
            ps.setString(6, "imagencolores.jpg");
            ps.setBoolean(7, true);
            ps.execute();
            JOptionPane.showMessageDialog(null, "El vendedor " +txtNombreVendedor.getText() + " fue registrado con éxito :)");
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
        {
            ps=null;
            conn=null;
            this.Vaciar();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        hide();
        LoginUsuario obl = new LoginUsuario();
        obl.setVisible(true);
    }//GEN-LAST:event_btnbackMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedorRegistros().setVisible(true);
            }
        });
    }
    
     private void Vaciar()
    {
        txtNombreVendedor.setText("");
        txtSexoVendedor.setText("");
        txtDomicilioVendedor.setText("");
        txtCorreoVendedor.setText("");
        txtContrasenaVendedor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroun;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel imgVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblContraseñaVendedor;
    private javax.swing.JLabel lblCorreoVendedor;
    private javax.swing.JLabel lblDomicilioVendedor;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreVendedor;
    private javax.swing.JLabel lblSexoVendedor;
    private javax.swing.JPasswordField txtContrasenaVendedor;
    private javax.swing.JTextField txtCorreoVendedor;
    private javax.swing.JTextField txtDomicilioVendedor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtSexoVendedor;
    // End of variables declaration//GEN-END:variables
}
