/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package papeleria;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristianss
 */
public class CategoriasProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CategoriasProductos
     */
    public CategoriasProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblColoresNombre = new javax.swing.JLabel();
        txtColoresNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDescripción = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblColoresCantidad = new javax.swing.JLabel();
        CmbBoxCantidad = new javax.swing.JComboBox<>();
        lblColoresCantidad1 = new javax.swing.JLabel();
        txtFormaColores = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblDescuento = new javax.swing.JLabel();
        CboxDescuento = new javax.swing.JCheckBox();
        lblCantidadDescuento = new javax.swing.JLabel();
        CmbBoxDescuentos = new javax.swing.JComboBox<>();
        IcnInsertarImagen = new javax.swing.JLabel();
        txtInsertarImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CategoriasBackGround = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        lblTitulo.setText(" Colores");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 150, -1));

        lblColoresNombre.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblColoresNombre.setText("Colores");
        getContentPane().add(lblColoresNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        txtColoresNombre.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtColoresNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtColoresNombre.setText("Ingrese la categoria");
        txtColoresNombre.setBorder(null);
        getContentPane().add(txtColoresNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 130, 10));

        lblDescripción.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblDescripción.setText("Descripción");
        getContentPane().add(lblDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        txtDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescripcion.setText("Ingrese una Descripción");
        txtDescripcion.setBorder(null);
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 310, 80));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, 230, 0));

        lblColoresCantidad.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblColoresCantidad.setText("Cantidad de Colores");
        getContentPane().add(lblColoresCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        CmbBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24", "32", "48", " " }));
        CmbBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBoxCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(CmbBoxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        lblColoresCantidad1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblColoresCantidad1.setText("Forma Colores");
        getContentPane().add(lblColoresCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 30));

        txtFormaColores.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtFormaColores.setForeground(new java.awt.Color(204, 204, 204));
        txtFormaColores.setText("Ingrese la forma");
        txtFormaColores.setBorder(null);
        txtFormaColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormaColoresActionPerformed(evt);
            }
        });
        getContentPane().add(txtFormaColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 130, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 130, 10));

        lblDescuento.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblDescuento.setForeground(new java.awt.Color(255, 255, 255));
        lblDescuento.setText("Descuento");
        getContentPane().add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        CboxDescuento.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CboxDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 20, 20));

        lblCantidadDescuento.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblCantidadDescuento.setForeground(new java.awt.Color(51, 51, 51));
        lblCantidadDescuento.setText("Cantidad a descontar");
        getContentPane().add(lblCantidadDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));

        CmbBoxDescuentos.setBackground(new java.awt.Color(227, 95, 30));
        CmbBoxDescuentos.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        CmbBoxDescuentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "7%", "12%", "15%" }));
        CmbBoxDescuentos.setBorder(null);
        getContentPane().add(CmbBoxDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        IcnInsertarImagen.setBackground(new java.awt.Color(204, 204, 204));
        IcnInsertarImagen.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        IcnInsertarImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IcnInsertarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insertar-icono-de-imagen.png"))); // NOI18N
        getContentPane().add(IcnInsertarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 240, 210));

        txtInsertarImagen.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtInsertarImagen.setForeground(new java.awt.Color(255, 255, 255));
        txtInsertarImagen.setText("Insertar Imagen del Producto");
        getContentPane().add(txtInsertarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgregar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 100, 40));

        CategoriasBackGround.setBackground(new java.awt.Color(0, 0, 0));
        CategoriasBackGround.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        CategoriasBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-Colores.png"))); // NOI18N
        getContentPane().add(CategoriasBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 290, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
        String consultaSQL;
        consultaSQL = "INSERT INTO Colores(MarcaColores, DescripcionColores, CantidadColores, FormaColores, banderadescuento,descuentoCategoria, imagenColores,activo)\n";
        consultaSQL +="VALUES(?,?,?,?,?,?,?,?)";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setString(1,txtColoresNombre.getText().trim());
        ps.setString(2, txtDescripcion.getText().trim());
        ps.setInt(3, (CmbBoxCantidad.getSelectedIndex())); //Aqui puede valer pito
        ps.setString(4, txtFormaColores.getText().trim());
        ps.setBoolean(5, CboxDescuento.isSelected());
        if(CboxDescuento.isSelected())
           ps.setInt(6, (CmbBoxDescuentos.getSelectedIndex()));  //Aqui puede valer pito
        else
            ps.setInt(6, 0);
        ps.setString(7, "imagencolores.jpg");
        ps.setBoolean(8, true);
        ps.execute();
        JOptionPane.showMessageDialog(null, "Colores" +txtColoresNombre.getText() + " agregados con éxito :)");
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CmbBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBoxCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbBoxCantidadActionPerformed

    private void txtFormaColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormaColoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormaColoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriasBackGround;
    private javax.swing.JCheckBox CboxDescuento;
    private javax.swing.JComboBox<String> CmbBoxCantidad;
    private javax.swing.JComboBox<String> CmbBoxDescuentos;
    private javax.swing.JLabel IcnInsertarImagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCantidadDescuento;
    private javax.swing.JLabel lblColoresCantidad;
    private javax.swing.JLabel lblColoresCantidad1;
    private javax.swing.JLabel lblColoresNombre;
    private javax.swing.JLabel lblDescripción;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtColoresNombre;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFormaColores;
    private javax.swing.JLabel txtInsertarImagen;
    // End of variables declaration//GEN-END:variables
}
