/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package papeleriayolis;

/**
 *
 * @author CSjes
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miRProductosNuevos = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        miMDatosProductos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        miImpresiones = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        miRVendedor = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        miISVendedor = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        miCSVendedor = new javax.swing.JMenuItem();
        miCSAdministrador = new javax.swing.JMenuItem();
        miCSCliente = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Inventario");

        jMenu8.setText("Visualizar");

        jMenuItem1.setText("Productos existentes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuItem2.setText("Productos sin stoke");
        jMenu8.add(jMenuItem2);

        jMenuItem3.setText("Productos proximos a terminarse");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenu3.add(jMenu8);

        jMenu9.setText("Registrar");

        miRProductosNuevos.setText("Productos nuevos");
        miRProductosNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRProductosNuevosActionPerformed(evt);
            }
        });
        jMenu9.add(miRProductosNuevos);

        jMenuItem5.setText("Productos con stoke");
        jMenu9.add(jMenuItem5);

        jMenu3.add(jMenu9);

        jMenu10.setText("Dar de baja");

        jMenuItem6.setText("Productos devueltos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenuItem7.setText("Productos rezagados");
        jMenu10.add(jMenuItem7);

        jMenu3.add(jMenu10);

        miMDatosProductos.setText("Modificar Datos");
        miMDatosProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMDatosProductosActionPerformed(evt);
            }
        });
        jMenu3.add(miMDatosProductos);

        menuBar.add(jMenu3);

        jMenu4.setText("Punto de cobro");

        jMenu11.setText("Venta");

        jMenuItem8.setText("Normal");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem8);

        jMenuItem9.setText("Mayoreo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem9);

        jMenu4.add(jMenu11);

        menuBar.add(jMenu4);

        jMenu5.setText("Servicios");

        jMenu12.setText("En linea");

        jMenuItem10.setText("Impresiones");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem10);

        jMenuItem11.setText("CURP");
        jMenu12.add(jMenuItem11);

        jMenuItem12.setText("RFC");
        jMenu12.add(jMenuItem12);

        jMenuItem13.setText("Acta de nacimiento");
        jMenu12.add(jMenuItem13);

        jMenu5.add(jMenu12);

        jMenu13.setText("Local");

        miImpresiones.setText("Impresiones");
        miImpresiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImpresionesActionPerformed(evt);
            }
        });
        jMenu13.add(miImpresiones);

        jMenuItem15.setText("Copias");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem15);

        jMenuItem16.setText("CURP");
        jMenu13.add(jMenuItem16);

        jMenuItem17.setText("RFC");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem17);

        jMenuItem18.setText("Acta de nacimiento");
        jMenu13.add(jMenuItem18);

        jMenu5.add(jMenu13);

        menuBar.add(jMenu5);

        jMenu6.setText("Usuarios");

        jMenu14.setText("Registrar");

        miRVendedor.setText("Vendedor");
        miRVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRVendedorActionPerformed(evt);
            }
        });
        jMenu14.add(miRVendedor);

        jMenuItem20.setText("Administrador inventario");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem20);

        jMenuItem21.setText("Cliente");
        jMenu14.add(jMenuItem21);

        jMenu6.add(jMenu14);

        jMenu15.setText("Iniciar Sesión ");

        miISVendedor.setText("Vendedor");
        miISVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miISVendedorActionPerformed(evt);
            }
        });
        jMenu15.add(miISVendedor);

        jMenuItem23.setText("Administrador inventario");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem23);

        jMenuItem24.setText("Cliente");
        jMenu15.add(jMenuItem24);

        jMenu6.add(jMenu15);

        jMenu16.setText("Cerrar Sesión");

        miCSVendedor.setText("Vendedor");
        miCSVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCSVendedorActionPerformed(evt);
            }
        });
        jMenu16.add(miCSVendedor);

        miCSAdministrador.setText("Administrador inventario");
        miCSAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCSAdministradorActionPerformed(evt);
            }
        });
        jMenu16.add(miCSAdministrador);

        miCSCliente.setText("Cliente");
        miCSCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCSClienteActionPerformed(evt);
            }
        });
        jMenu16.add(miCSCliente);

        jMenu6.add(jMenu16);

        jMenu17.setText("Dar de baja");

        jMenuItem28.setText("Vendedor");
        jMenu17.add(jMenuItem28);

        jMenuItem29.setText("Administrador inventario");
        jMenu17.add(jMenuItem29);

        jMenuItem30.setText("Cliente");
        jMenu17.add(jMenuItem30);

        jMenu6.add(jMenu17);

        jMenu18.setText("Modificar Datos");

        jMenuItem31.setText("Vendedor");
        jMenu18.add(jMenuItem31);

        jMenuItem32.setText("Administrador inventario");
        jMenu18.add(jMenuItem32);

        jMenuItem33.setText("Cliente");
        jMenu18.add(jMenuItem33);

        jMenu6.add(jMenu18);

        menuBar.add(jMenu6);

        jMenu7.setText("Salir");

        jMenuItem35.setText("Cerrar Aplicación");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem35);

        menuBar.add(jMenu7);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void miImpresionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImpresionesActionPerformed
        Impresiones obi = new Impresiones();
        escritorio.add(obi);
        obi.setVisible(true);
    }//GEN-LAST:event_miImpresionesActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void miCSVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCSVendedorActionPerformed
        CerrarSesionVendedor obcsv = new CerrarSesionVendedor();
        escritorio.add(obcsv);
        obcsv.setVisible(true);
    }//GEN-LAST:event_miCSVendedorActionPerformed

    private void miMDatosProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMDatosProductosActionPerformed
        ModificarDatosProductos obmdp = new ModificarDatosProductos();
        escritorio.add(obmdp);
        obmdp.setVisible(true);
    }//GEN-LAST:event_miMDatosProductosActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void miRProductosNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRProductosNuevosActionPerformed
        RegistrarProductosNuevos obrpn = new RegistrarProductosNuevos();
        escritorio.add(obrpn);
        obrpn.setVisible(true);
    }//GEN-LAST:event_miRProductosNuevosActionPerformed

    private void miRVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRVendedorActionPerformed
        RegistrarVendedor obrv = new RegistrarVendedor();
        escritorio.add(obrv);
        obrv.setVisible(true);
    }//GEN-LAST:event_miRVendedorActionPerformed

    private void miISVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miISVendedorActionPerformed
        IniciarSesionVendedor obisv = new IniciarSesionVendedor();
        escritorio.add(obisv);
        obisv.setVisible(true);
    }//GEN-LAST:event_miISVendedorActionPerformed

    private void miCSAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCSAdministradorActionPerformed
        CerrarSesionAdministrador obcsa = new CerrarSesionAdministrador();
        escritorio.add(obcsa);
        obcsa.setVisible(true);
    }//GEN-LAST:event_miCSAdministradorActionPerformed

    private void miCSClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCSClienteActionPerformed
        CerrarSesionCliente obcsc = new CerrarSesionCliente();
        escritorio.add(obcsc);
        obcsc.setVisible(true);
    }//GEN-LAST:event_miCSClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miCSAdministrador;
    private javax.swing.JMenuItem miCSCliente;
    private javax.swing.JMenuItem miCSVendedor;
    private javax.swing.JMenuItem miISVendedor;
    private javax.swing.JMenuItem miImpresiones;
    private javax.swing.JMenuItem miMDatosProductos;
    private javax.swing.JMenuItem miRProductosNuevos;
    private javax.swing.JMenuItem miRVendedor;
    // End of variables declaration//GEN-END:variables

}
