/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package papeleriayolis;

/**
 *
 * @author CSjes
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jbMenuUsuarios = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbMenuPuntoCobro = new javax.swing.JButton();
        jbMenuInventario = new javax.swing.JButton();
        jbMenuServicios = new javax.swing.JButton();
        jbDesplegarMenu = new javax.swing.JButton();
        jbCerrrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 159, 220));
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(1, 159, 220));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(252, 195, 20));

        jbMenuUsuarios.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuUsuarios.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuUsuarios.setText("Usuarios");
        jbMenuUsuarios.setBorder(null);
        jbMenuUsuarios.setContentAreaFilled(false);
        jbMenuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuUsuariosMouseClicked(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(252, 195, 20));
        jbSalir.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.setBorder(null);
        jbSalir.setContentAreaFilled(false);

        jbMenuPuntoCobro.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuPuntoCobro.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuPuntoCobro.setText("Punto de Cobro");
        jbMenuPuntoCobro.setBorder(null);
        jbMenuPuntoCobro.setContentAreaFilled(false);
        jbMenuPuntoCobro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuPuntoCobroMouseClicked(evt);
            }
        });
        jbMenuPuntoCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuPuntoCobroActionPerformed(evt);
            }
        });

        jbMenuInventario.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuInventario.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuInventario.setText("Inventario");
        jbMenuInventario.setBorder(null);
        jbMenuInventario.setContentAreaFilled(false);
        jbMenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuInventarioMouseClicked(evt);
            }
        });

        jbMenuServicios.setBackground(new java.awt.Color(252, 195, 20));
        jbMenuServicios.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbMenuServicios.setText("Servicios");
        jbMenuServicios.setBorder(null);
        jbMenuServicios.setContentAreaFilled(false);
        jbMenuServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuServiciosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbMenuUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbMenuPuntoCobro, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(jbMenuServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbMenuInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jbMenuInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbMenuPuntoCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbMenuServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbMenuUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel5.add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, -1, 520));

        jbDesplegarMenu.setBackground(new java.awt.Color(1, 159, 220));
        jbDesplegarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menubuttonofthreelinesoutline_112563.png"))); // NOI18N
        jbDesplegarMenu.setBorder(null);
        jbDesplegarMenu.setContentAreaFilled(false);
        jbDesplegarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesplegarMenuActionPerformed(evt);
            }
        });
        jPanel5.add(jbDesplegarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 60, 60));

        jbCerrrar.setBackground(new java.awt.Color(2, 159, 220));
        jbCerrrar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jbCerrrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrrar.setText("X");
        jbCerrrar.setBorder(null);
        jbCerrrar.setContentAreaFilled(false);
        jbCerrrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrrarActionPerformed(evt);
            }
        });
        jPanel5.add(jbCerrrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDesplegarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesplegarMenuActionPerformed
        int posicion = jbDesplegarMenu.getX();
        if(posicion>5)
        {
            Animacion.Animacion.mover_izquierda(261, 5, 2, 2, jbDesplegarMenu);
            Animacion.Animacion.mover_izquierda(5, -260, 2, 2, jpMenu);
        }
        else
        {
            Animacion.Animacion.mover_derecha(5, 260, 2, 2, jbDesplegarMenu);
            Animacion.Animacion.mover_derecha(-260, 5, 2, 2, jpMenu);
        }
    }//GEN-LAST:event_jbDesplegarMenuActionPerformed

    private void jbCerrrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbCerrrarActionPerformed

    private void jbMenuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuInventarioMouseClicked
        dispose();
        MenuInventario obmi = new MenuInventario();
        obmi.setVisible(true);
    }//GEN-LAST:event_jbMenuInventarioMouseClicked

    private void jbMenuPuntoCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuPuntoCobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMenuPuntoCobroActionPerformed

    private void jbMenuPuntoCobroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuPuntoCobroMouseClicked
        dispose();
        MenuPuntoCobro obmpc = new MenuPuntoCobro();
        obmpc.setVisible(true);
    }//GEN-LAST:event_jbMenuPuntoCobroMouseClicked

    private void jbMenuServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuServiciosMouseClicked
        dispose();
        MenuServicios obms = new MenuServicios();
        obms.setVisible(true);
    }//GEN-LAST:event_jbMenuServiciosMouseClicked

    private void jbMenuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuUsuariosMouseClicked
        dispose();
        MenuUsuarios obmu = new MenuUsuarios();
        obmu.setVisible(true);
    }//GEN-LAST:event_jbMenuUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbCerrrar;
    private javax.swing.JButton jbDesplegarMenu;
    private javax.swing.JButton jbMenuInventario;
    private javax.swing.JButton jbMenuPuntoCobro;
    private javax.swing.JButton jbMenuServicios;
    private javax.swing.JButton jbMenuUsuarios;
    private javax.swing.JButton jbSalir;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables

}
