/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package papeleriayolis;
import database.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo Campos L
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        imgVendedor = new javax.swing.JLabel();
        lblNombrePro = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblcodigo = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        txtCompra = new javax.swing.JTextField();
        lblCorreoVendedor = new javax.swing.JLabel();
        txtVenta = new javax.swing.JTextField();
        lblContraseñaVendedor = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        Backgroun = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, 10));

        imgVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        imgVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/products128px.png"))); // NOI18N
        add(imgVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 130, 130));

        lblNombrePro.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblNombrePro.setText("Nombre :");
        add(lblNombrePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, -1));

        txtNombre.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtNombre.setBorder(null);
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));

        lblcodigo.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblcodigo.setText("Éxistencia:");
        add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, -1));

        txtExistencia.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtExistencia.setBorder(null);
        txtExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistenciaActionPerformed(evt);
            }
        });
        add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, -1));

        lbltelefono.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lbltelefono.setText("Precio Compra:");
        add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, -1));

        txtCompra.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtCompra.setBorder(null);
        txtCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompraActionPerformed(evt);
            }
        });
        add(txtCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));

        lblCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblCorreoVendedor.setText("Precio Venta:");
        add(lblCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        txtVenta.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtVenta.setBorder(null);
        add(txtVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 140, -1));

        lblContraseñaVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblContraseñaVendedor.setText("Categoria :");
        add(lblContraseñaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, -1));

        txtCategoria.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtCategoria.setBorder(null);
        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, -1));

        lblID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblID.setText("ID :");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 20, -1));

        txtID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtID.setBorder(null);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 70, -1));

        btnBuscar.setBackground(new java.awt.Color(254, 192, 15));
        btnBuscar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 70, -1));

        btnAgregar.setBackground(new java.awt.Color(254, 192, 15));
        btnAgregar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 70, -1));

        btnEliminar.setBackground(new java.awt.Color(254, 192, 15));
        btnEliminar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 70, -1));

        btnActualizar.setBackground(new java.awt.Color(254, 192, 15));
        btnActualizar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 70, 20));

        Backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoVendedores.png"))); // NOI18N
        add(Backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 230, 460));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel1.setText("Productos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExistenciaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Conexion conn = Conexion.getInstance();
        encontrado = false;
        PreparedStatement ps;
        ResultSet rs;
        String consultaSQL = "select nombreProducto,Existencias,PrecioCompra,PrecioVenta,Categoria from Productos where idProductos=?;";
        try {
            conn.Conectar();
            ps = conn.cadena.prepareStatement(consultaSQL);
            ps.setInt(1, Integer.valueOf(txtID.getText()));
            rs = ps.executeQuery();
            if (rs.next()) {
                this.encontrado = true;
                txtNombre.setText(rs.getString(1));
                txtExistencia.setText(rs.getString(2));
                txtCompra.setText(rs.getString(3));
                txtVenta.setText(rs.getString(4));
                txtCategoria.setText(rs.getString(5));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro el producto");
            }
            rs.close();
            ps.close();
            conn.Desconectar();
            conn.cadena.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            ps = null;
            conn = null;
            rs = null;
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion conn = Conexion.getInstance();
        PreparedStatement ps;
        String consultaSQL = "insert into Productos(nombreProducto, Existencias, PrecioCompra, PrecioVenta,Categoria  )\n"
        + "values(?,?,?,?,?) ;";
        try {
            conn.Conectar();
            ps = conn.cadena.prepareStatement(consultaSQL);
            ps.setString(1, txtNombre.getText().trim());
            ps.setInt(2, Integer.parseInt(txtExistencia.getText()));
            ps.setDouble(3, Double.parseDouble(txtCompra.getText()));
            ps.setDouble(4, Double.parseDouble(txtVenta.getText()));
            ps.setString(5, txtCategoria.getText().trim());
            ps.execute();
            ps.close();
            conn.Desconectar();
            conn.cadena.close();
            JOptionPane.showMessageDialog(null, "Nuevo producto registrado");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            ps = null;
            conn = null;
        }
        this.Limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Conexion conn = Conexion.getInstance();
        PreparedStatement ps;
        if (txtID.getText().equals("") || encontrado == false) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un producto");
            txtID.requestFocus();
            return;
        }
        String consultaSQL = "delete from Productos where idProductos=?;";
        try {
            conn.Conectar();
            ps = conn.cadena.prepareStatement(consultaSQL);
            ps.setInt(1, Integer.valueOf(txtID.getText()));
            if (ps.executeUpdate() == 1) {
                this.encontrado = false;
                JOptionPane.showMessageDialog(null, "El producto a sido eliminado");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro el producto");
            }
            ps.close();
            conn.Desconectar();
            conn.cadena.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            ps = null;
            conn = null;
        }
        this.Limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Conexion conn = Conexion.getInstance();
        PreparedStatement ps;
        if (txtID.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoria");
            txtID.requestFocus();
            return;
        }
        String consultaSQL = "update Productos set nombreProducto=?,Existencias=?,PrecioCompra=?,PrecioVenta=?,Categoria=? where idProductos=?;";
        try {
            conn.Conectar();
            ps = conn.cadena.prepareStatement(consultaSQL);
            ps.setString(1, txtNombre.getText().trim());
            ps.setInt(2, Integer.valueOf(txtExistencia.getText()));
            ps.setDouble(3, Double.valueOf(txtCompra.getText()));
            ps.setDouble(4, Double.valueOf(txtVenta.getText()));
            ps.setString(5, txtCategoria.getText());
            ps.setInt(6, Integer.valueOf(txtID.getText()));
            if (ps.executeUpdate() == 1) {
                this.encontrado = false;
                JOptionPane.showMessageDialog(null, "La categoria ha sido actualizada");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la categoria");
            }
            ps.close();
            conn.Desconectar();
            conn.cadena.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            ps = null;
            conn = null;
        }
        this.Limpiar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompraActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed
 public void Limpiar() {
        txtNombre.setText("");
        txtExistencia.setText("");
        txtCompra.setText("");
        txtVenta.setText("");
        txtCategoria.setText("");
        txtID.setText("");
    }
 public boolean encontrado = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroun;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel imgVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblContraseñaVendedor;
    private javax.swing.JLabel lblCorreoVendedor;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombrePro;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
