/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package papeleria;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Cristianss
 */
public class Vendedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendedores
     */
    public Vendedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreVendedor = new javax.swing.JLabel();
        txtNombreVendedor = new javax.swing.JTextField();
        lblSexoVendedor = new javax.swing.JLabel();
        txtSexoVendedor = new javax.swing.JTextField();
        lblDomicilioVendedor = new javax.swing.JLabel();
        txtDomicilioVendedor = new javax.swing.JTextField();
        lblCorreoVendedor = new javax.swing.JLabel();
        txtCorreoVendedor = new javax.swing.JTextField();
        lblContraseñaVendedor = new javax.swing.JLabel();
        txtContraseñaVendedor = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        imgVendedor = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        Backgroun = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblNombreVendedor.setText("Nombre :");
        getContentPane().add(lblNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, -1));

        txtNombreVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, -1));

        lblSexoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblSexoVendedor.setText("Sexo :");
        getContentPane().add(lblSexoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, -1));

        txtSexoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtSexoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSexoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, -1));

        lblDomicilioVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblDomicilioVendedor.setText("Domicilio :");
        getContentPane().add(lblDomicilioVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, -1));

        txtDomicilioVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtDomicilioVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        lblCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblCorreoVendedor.setText("Correo :");
        getContentPane().add(lblCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, -1));

        txtCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, -1));

        lblContraseñaVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblContraseñaVendedor.setText("Contraseña :");
        getContentPane().add(lblContraseñaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, -1));

        txtContraseñaVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtContraseñaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, -1));

        lblID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblID.setText("ID :");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 20, -1));

        txtID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, -1));

        imgVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        imgVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil (1).png"))); // NOI18N
        getContentPane().add(imgVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, 130));

        btnBuscar.setBackground(new java.awt.Color(254, 192, 15));
        btnBuscar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 70, -1));

        btnAgregar.setBackground(new java.awt.Color(254, 192, 15));
        btnAgregar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, -1));

        btnEliminar.setBackground(new java.awt.Color(254, 192, 15));
        btnEliminar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 70, -1));

        Backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoVendedores.png"))); // NOI18N
        getContentPane().add(Backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 200, 350));

        btnActualizar.setBackground(new java.awt.Color(254, 192, 15));
        btnActualizar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Vaciar()
    {
        txtNombreVendedor.setText("");
        txtSexoVendedor.setText("");
        txtDomicilioVendedor.setText("");
        txtCorreoVendedor.setText("");
        txtContraseñaVendedor.setText("");
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
        ResultSet rs; //Guardar resultado de una consulta
         if( txtID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoría");
            txtID.requestFocus();
            return;
        }
        String consultaSQL="SELECT NombreVendedor,SexoVendedor, DomicilioVendedor, CorreoVendedor, ContrasenaVendedor FROM Vendedores WHERE idVendedor=?;";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setInt(1,Integer.valueOf(txtID.getText()));
        rs=ps.executeQuery();
        if(rs.next())
        {
            txtNombreVendedor.setText(rs.getString(1));
            txtSexoVendedor.setText(rs.getString(2));
            txtDomicilioVendedor.setText(rs.getString(3));
            txtCorreoVendedor.setText(rs.getString(4));
            txtContraseñaVendedor.setText(rs.getString(5));
        }
            else
            JOptionPane.showMessageDialog(null, "No se encontro el vendedor  :( ");
        ps.close();
        rs.close();
        conn.Desconectar();
        conn.cadena.close();
        
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            finally
            {
            ps=null;
            rs=null;
            conn=null;
            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
         if( txtID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoría");
            txtID.requestFocus();
            return;
        }
        String consultaSQL;
        consultaSQL = "INSERT INTO Vendedores(NombreVendedor,SexoVendedor, DomicilioVendedor, CorreoVendedor, ContrasenaVendedor,ImagenVendedor, activo)\n";
        consultaSQL +="VALUES(?,?,?,?,?,?,?)";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setString(1,txtNombreVendedor.getText().trim());
        ps.setString(2, txtSexoVendedor.getText().trim());
        ps.setString(3, txtDomicilioVendedor.getText().trim()); 
        ps.setString(4, txtCorreoVendedor.getText().trim());
        ps.setString(5, txtContraseñaVendedor.getText().trim());
        ps.setString(6, "imagencolores.jpg");
        ps.setBoolean(7, true);
        ps.execute();
        JOptionPane.showMessageDialog(null, "El vendedor " +txtNombreVendedor.getText() + " fue registrado con éxito :)");
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
            {
            ps=null;
            conn=null;
            this.Vaciar();
            }
                                        

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtSexoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoVendedorActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
         if( txtID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoría");
            txtID.requestFocus();
            return;
        }
        String consultaSQL="DELETE FROM Vendedores WHERE idVendedor=?;";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setInt(1,Integer.valueOf(txtID.getText()));
        if(ps.executeUpdate()==1)
        {
            this.encontrado=false;
            JOptionPane.showMessageDialog(null, "El vendedor ha sido eliminado :b");
            
            
        }
            else
            JOptionPane.showMessageDialog(null, "No se encontro el vendedor  :( ");
        ps.close();
        
        conn.Desconectar();
        conn.cadena.close();
        
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            finally
            {
            ps=null;
            conn=null;
            this.Vaciar();
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
         if( txtID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoría");
            txtID.requestFocus();
            return;
        }
        String consultaSQL="UPDATE Vendedores SET NombreVendedor=?, SexoVendedor=?, DomicilioVendedor=?, CorreoVendedor=?, ContrasenaVendedor=? WHERE idVendedor=?;";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setString(1,txtNombreVendedor.getText().trim());
        ps.setString(2,txtSexoVendedor.getText().trim());
        ps.setString(3,txtDomicilioVendedor.getText().trim());
        ps.setString(4,txtCorreoVendedor.getText().trim());
        ps.setString(5,txtContraseñaVendedor.getText());
        ps.setInt(6,Integer.valueOf(txtID.getText()));
       
        if(ps.executeUpdate()==1)
        {
            this.encontrado=false;
            JOptionPane.showMessageDialog(null, "El vendedor ha sido actualizado :b");
            
            
        }
            else
            JOptionPane.showMessageDialog(null, "No se encontro el vendedor  :( ");
        ps.close();
        
        conn.Desconectar();
        conn.cadena.close();
        
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            finally
            {
            ps=null;
            conn=null;
            this.Vaciar();
            }
    }//GEN-LAST:event_btnActualizarActionPerformed

    boolean encontrado = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroun;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel imgVendedor;
    private javax.swing.JLabel lblContraseñaVendedor;
    private javax.swing.JLabel lblCorreoVendedor;
    private javax.swing.JLabel lblDomicilioVendedor;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreVendedor;
    private javax.swing.JLabel lblSexoVendedor;
    private javax.swing.JTextField txtContraseñaVendedor;
    private javax.swing.JTextField txtCorreoVendedor;
    private javax.swing.JTextField txtDomicilioVendedor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtSexoVendedor;
    // End of variables declaration//GEN-END:variables
}
